export const featuredItems = [
  {
    name: "Cold brew",
    description: "Brewed slowly for a smooth",
    price: "$3.00",
    image: "/assets/images/featured/col-brew.avif",
    new: false,
  },
  {
    name: "Grilled cheese",
    description: "It is a classic comfort food with melted cheddar.",
    price: "$3.55",
    image: "/assets/images/featured/grilled-cheese.avif",
    new: false,
  },
  {
    name: "Chocolate cake",
    description: "A rich and moist chocolate cake topped with creamy",
    price: "$2.95",
    image: "/assets/images/featured/chocolate-cake.avif",
    new: true,
  },
  {
    name: "Latte",
    description: "Smooth and creamy",
    price: "$2.15",
    image: "/assets/images/featured/latte.avif",
    new: false,
  },
  {
    name: "Espresso delight",
    description: "A rich and bold espresso shot.",
    price: "$2.95",
    image: "/assets/images/featured/espress-delight.avif",
    new: false,
  },
  {
    name: "Matcha latte",
    description: "A creamy and vibrant green tea",
    price: "$1.80",
    image: "/assets/images/featured/macha--latte.avif",
    new: true,
  },
  {
    name: "Caesar salad",
    description: "Crisp romaine lettuce tossed with Caesar dressing.",
    price: "$2.00",
    image: "/assets/images/featured/caeser-salad.avif",
    new: false,
  },
  {
    name: "Almond croissant",
    description: "A buttery, flaky croissant filled with a rich almond",
    price: "$5.80",
    image: "/assets/images/featured/almond-croissant.avif",
    new: false,
  },
];

export const lunchItems = [
  {
    name: "Grilled Chicken Sandwich",
    description: "Juicy grilled chicken breast with lettuce and tomato.",
    price: "$5.95",
    image: "/assets/images/featured/grilled-chicken-sandwich.jpg",
    new: false,
  },
  {
    name: "Veggie Wrap",
    description: "A mix of grilled vegetables with hummus in a wrap.",
    price: "$4.80",
    image: "/assets/images/featured/veggie-wrap.avif",
    new: true,
  },
  {
    name: "Turkey Club",
    description: "Classic turkey sandwich with crispy bacon and mayo.",
    price: "$6.50",
    image: "/assets/images/featured/turkey-club.avif",
    new: false,
  },
  {
    name: "Caesar Salad",
    description: "Romaine lettuce with Caesar dressing and croutons.",
    price: "$4.25",
    image: "/assets/images/featured/caeser-salad.avif",
    new: false,
  },
  {
    name: "Grilled Panini",
    description: "Pressed sandwich with cheese, tomato, and basil.",
    price: "$5.30",
    image: "/assets/images/featured/grilled--panini.avif",
    new: true,
  },
  {
    name: "Lentil Soup",
    description: "Hearty soup made with lentils, carrots, and herbs.",
    price: "$3.90",
    image: "/assets/images/featured/lentil-soup.avif",
    new: false,
  },
  {
    name: "Chicken Quesadilla",
    description: "Grilled tortilla filled with chicken and melted cheese.",
    price: "$5.75",
    image: "/assets/images/featured/chicken-quesadilla.avif",
    new: false,
  },
  {
    name: "Greek Bowl",
    description: "Rice bowl with chicken, feta, olives, and tzatziki.",
    price: "$6.20",
    image: "/assets/images/featured/greek-bowl.avif",
    new: true,
  },
];

export const dinnerItems = [
  {
    name: "BBQ Ribs",
    description: "Tender pork ribs glazed with smoky BBQ sauce.",
    price: "$9.95",
    image: "/assets/images/featured/bbq-ribs.avif",
    new: true,
  },
  {
    name: "Spaghetti Bolognese",
    description: "Classic Italian pasta with rich meat sauce.",
    price: "$7.85",
    image: "/assets/images/featured/spagetti-bolognesse.avif",
    new: false,
  },
  {
    name: "Grilled Salmon",
    description: "Salmon fillet with lemon butter sauce and veggies.",
    price: "$10.50",
    image: "/assets/images/featured/grilled-salmon.avif",
    new: false,
  },
  {
    name: "Beef Stir Fry",
    description: "Sautéed beef with mixed vegetables and soy glaze.",
    price: "$8.60",
    image: "/assets/images/featured/beed-stir-fry.avif",
    new: false,
  },
  {
    name: "Mushroom Risotto",
    description: "Creamy risotto with wild mushrooms and parmesan.",
    price: "$7.50",
    image: "/assets/images/featured/mushroom-resotto.avif",
    new: true,
  },
  {
    name: "Roast Chicken",
    description: "Herb-roasted chicken with mashed potatoes.",
    price: "$8.90",
    image: "/assets/images/featured/roast-chicken.avif",
    new: false,
  },
  {
    name: "Shrimp Tacos",
    description: "Spicy grilled shrimp with slaw and lime crema.",
    price: "$6.80",
    image: "/assets/images/featured/shrimp-tacos.avif",
    new: false,
  },
  {
    name: "Stuffed Bell Peppers",
    description: "Bell peppers filled with rice, meat, and herbs.",
    price: "$6.40",
    image: "/assets/images/featured/stuffed--bell-peppers.avif",
    new: true,
  },
];
